# Generated by Django 4.1.3 on 2022-12-24 05:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_auto_20210322_0021"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="current_bid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name="item",
            name="winner",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="item",
            name="watchers",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="itemcategory",
            name="name",
            field=models.CharField(
                choices=[
                    ("Vehicles", "Vehicles"),
                    ("Sport", "Sport"),
                    ("Electronics", "Electronics"),
                    ("Accessories", "Accessories"),
                    ("Other", "Others"),
                ],
                max_length=25,
            ),
        ),
    ]
